### ISSUE TITLE
Pact port setting ignored

### ISSUE THREAD

**Issue by KeNaCo** [reecetech/pactman#3]
Hi, I tried consumer example test from readme and run into couple of problems with ports.

First I test exactly copy-paste version of consumer test. And it fails. First inconsistency is in test itself:
```python
response = requests.get(f'http://service.example/users/{user_name}')
```
Then I look at [Consumer.has_pact_with](https://github.com/reecetech/pactman/blob/master/pactman/mock/consumer.py#L39) definition and find out that default port is 1234.

After update test still fail. Then I found that mock listen on port 8155. Which is constant from [Config](https://github.com/reecetech/pactman/blob/master/pactman/mock/pact_request_handler.py#L26) object. This constant can't be overriden by explicit port definition.

This test pass, which I suppose is not correct:
```python
def get_user(user_name):
    return requests.get(f'http://localhost:8155/users/{user_name}').json()

pact = Consumer('Consumer').has_pact_with(Provider('Provider'), port=10000, use_mocking_server=True)
```

Can you please verify this is a bug?
I am able to provide PM with fix after bug verification.

**Comment by richard-reece** [comment]
Hi Ken, thanks for the report. The intention with the mock server is that you replace the entire host:port specification with the pact.uri value which contains the location of the mocking server, host:port. What we tend to do in this case was configure the remote host using a lookup system:

config.py:
```
def get_service_url():
    return os.environ['SERVICE_URL']
```
user.py:
```
import config
def get_user(user_name):
    return requests.get(f'http://{config.get_service_url()}/users/{user_name}').json()
```
and then in your test:
```
pact = Consumer('Consumer').has_pact_with(Provider('Provider'), use_mocking_server=True)
pact.start_mocking()
atexit.register(pact.stop_mocking)

def test_get_user(monkeypatch):
    monkeypatch.setattr(config, 'get_service_url', lambda: pact.uri)
    with pact:
        get_user('pat')
```

Note that since you're using requests for your server calls you might find it easier to not use the mocking server - the default is to mock the code underlying requests (which is what we do, the above is the pattern we used before we had the direct mocking ability).

Note: the inability to explicitly set the port is indeed a bug, but the above still holds 👍

**Comment by KeNaCo** [comment]
Thank you for clarification.
