### ISSUE TITLE
can i use this to verify my django api provider and reactjs consumer?

### ISSUE THREAD

**Issue by simkimsia** [reecetech/pactman#72]
I literally just learned the term consumer driven contracts today.

I have a project that uses django as API provider and reactjs consumer clients.

They have their own separate unit tests, but sometimes, there is a slipup in terms of communicating what fields are expected.

Can I use this library to generate the right unt tests to ensure both provider (django) and consumer (react) are in sync?

**Comment by RobbieClarken** [comment]
Hi @simkimsia,

Yes, you can certainly use Pact testing to accomplish what you describe. You would integrate [pact-js](https://github.com/pact-foundation/pact-js) into your React unit tests to mock out calls to your backend. This will generate a json contract describing the requests your frontend will make and how it expects the backend to respond. You would then publish this contract to the [pact broker](https://github.com/pact-foundation/pact_broker). Finally, you would configure your Django tests to verify this contract using pactman. If you are using pytest to run your backend tests, you can utilise the fixture [described in the readme](https://github.com/reecetech/pactman#verifying-pacts-using-pytest).

Btw, an alternative to contract testing is to do e2e testing using a tool like Cypress. If you only have a single consumer and provider, this approach may actually be simpler and give faster feedback.

**Comment by simkimsia** [comment]
>Btw, an alternative to contract testing is to do e2e testing using a tool like Cypress. If you only have a single consumer and provider, this approach may actually be simpler and give faster feedback.

I am unsure what you mean by single consumer and provider. My Django is in its own github repo and so is the reactJs client which will be published in its own private npm. Therefore, total two github repo.
 
Does that fit what you say by single consumer and provider?

By the way, is anybody available for consulting? I am willing to pay for like an hour of consultation (as in I ask questions for answers. no coding required) so I know how to get either the cypress or the pactman portion working for my project.

**Comment by RobbieClarken** [comment]
> I am unsure what you mean by single consumer and provider. My Django is in its own github repo and so is the reactJs client which will be published in its own private npm. Therefore, total two github repo.
> Does that fit what you say by single consumer and provider?

Yes, in your case the frontend is considered the consumer and your backend is the provider (I should have said "single consumer, single provider"). Contrast this with a microservice environment where a service may have many consumers.

Contract testing is extremely valuable when you have many consumers because at some point it becomes infeasible to run end-to-end or integration tests on all the consumers whenever the provider code is updated. So instead the consumers each declare contracts that they expect the provider to fulfil and when the provider is updated we verify it hasn't broken any of the contracts.

> By the way, is anybody available for consulting? I am willing to pay for like an hour of consultation (as in I ask questions for answers. no coding required) so I know how to get either the cypress or the pactman portion working for my project.

I'm not sure about consulting but the Pact Foundation has a Slack where you can ask questions: https://slack.pact.io/.

**Comment by simkimsia** [comment]
Thanks, I suppose that means my question is answered. I will check on cypress first
