### ISSUE TITLE
Provider side Testing

### ISSUE THREAD

**Issue by Mukheem** [reecetech/pactman#83]
Team,

Can you update the documentation to make Provider side testing easier to understand.

Current example shows that when a django server is used as provider server on which we have the provider states setup ready.

It would have been easier for us easier to understand if things were made clear such as using a different server for Provider states set up and then different Live Provider Server.

It is even difficult to understand what parameters does pact_verifier accept and how to use it.

In my case, My test is succeeded via CLI. but I could not succeed thru code.

My CLI command is `pactman-verifier -l C:\Users\*****\PycharmProjects\pact-python-master\Pact\ConsumerPOC-Provider-pact.json Provider http://localhost:8081/ http://localhost:8082/setup`

I followed the documentation command `pactman-verifier -l /tmp/localpact.json                                                                     <provider name> <provider url> <provider setup url>` to get this done. Now I am not able to proceed with code to read all pacts from a local directory and then replay it against provider.

Any help would be greatly appreciated. 

Thanks.

**Comment by ryallsa** [comment]
Thanks for contacting Registers of Scotland, your email has been delivered to your intended recipient(s), who will be in touch as soon as they can.

In order to focus on safeguarding the wellbeing of our staff, maintaining our essential business activity, and operating in accordance with government guidelines during this public health emergency, we ask that you direct your enquiries as follows:

A specific case or enquiry – please resend your email to our Customer Services<mailto:customer.services@ros.gov.uk> team who will be in touch.

Any other general enquiry – please resend your email to Covid19enquiries@ros.gov.uk so it can be directed to the correct person.

Thank You

- - - - - - - - - - - - - - - - - - -
Registers of Scotland
- - - - - - - - - - - - - - - - - - -

www.ros.gov.uk<https://www.ros.gov.uk>

[cid:image9b2665.PNG@c1a4c2ad.4fb8c30c]<https://www.ros.gov.uk/>    [cid:image510a21.PNG@613083fb.4fba2233] <https://www.facebook.com/registersofscotland/>   [cid:image28abf4.PNG@857fefe2.42b55587] <https://twitter.com/RegistersOfScot>   [cid:image8a870c.PNG@3362930f.42830ecc] <https://www.youtube.com/channel/UCsvdb1Mw7n-shANwtFxrDMQ>   [cid:image2849f4.PNG@f5374be8.42ac5e94] <https://www.linkedin.com/authwall?trk=gf&trkInfo=AQEFPBtu7CCWwQAAAWNewfqoDlR1tdKRE7wGUu67suRzsyti8TMecqKnr1l97Cm06GPZkKXX2TXzf5g1bQO13VHKbYipr9Tf136ULQZRIGWkYOfOjp8PupaH9JDvdmTdxeUFykI=&originalReferer=&sessionRedirect=https%3A%2F%2Fwww.linkedin.com%2Fcompany%2Fregisters-of-scotland>

Please consider the environment – do you really need to print this email?

This e-mail (and any files or other attachments transmitted with it) is intended solely for the attention of the addressee(s). Unauthorised use, disclosure, storage, copying or distribution of any part of this e-mail is not permitted. If you are not the intended recipient please destroy the email, remove any copies from your system and inform the sender immediately by return. 

Registers of Scotland does not accept any liability or responsibility for any damage caused by any virus transmitted by this email or for changes made to this e-mail after it was sent. 
All communications to or from Registers of Scotland may be automatically logged, monitored and/or recorded in order to secure the effective operation of the system and for other lawful purposes. The views or opinions contained within this e-mail may not necessarily reflect those of the Keeper of the Registers of Scotland.

**Comment by r1chardj0n3s** [comment]
It really doesn't matter where the server setup is done, as long as it can manipulate the provider server's state. 

I am not sure what you mean by "Now I am not able to proceed with code to read all pacts from a local directory and then replay it against provider." `pactman-verifier` reads the pact and verifies it against the provider. You don't need to read the pact.

I have corrected the link to the pact documentation on provider states in the README (https://docs.pact.io/provider/using_provider_states_effectively)

**Comment by ryallsa** [comment]
Thanks for contacting Registers of Scotland, your email has been delivered to your intended recipient(s), who will be in touch as soon as they can.

In order to focus on safeguarding the wellbeing of our staff, maintaining our essential business activity, and operating in accordance with government guidelines during this public health emergency, we ask that you direct your enquiries as follows:

A specific case or enquiry – please resend your email to our Customer Services<mailto:customer.services@ros.gov.uk> team who will be in touch.

Any other general enquiry – please resend your email to Covid19enquiries@ros.gov.uk so it can be directed to the correct person.

Thank You

- - - - - - - - - - - - - - - - - - -
Registers of Scotland
- - - - - - - - - - - - - - - - - - -

www.ros.gov.uk<https://www.ros.gov.uk>

[cid:imageedde9e.PNG@97e06653.46babf49]<https://www.ros.gov.uk/>    [cid:image91c636.PNG@a7911279.4f9c63db] <https://www.facebook.com/registersofscotland/>   [cid:imagefbfba0.PNG@76ab51e6.4db661a4] <https://twitter.com/RegistersOfScot>   [cid:image24adca.PNG@8d021f4f.4b867262] <https://www.youtube.com/channel/UCsvdb1Mw7n-shANwtFxrDMQ>   [cid:image8ed5f6.PNG@47c0a422.4d87b1e2] <https://www.linkedin.com/authwall?trk=gf&trkInfo=AQEFPBtu7CCWwQAAAWNewfqoDlR1tdKRE7wGUu67suRzsyti8TMecqKnr1l97Cm06GPZkKXX2TXzf5g1bQO13VHKbYipr9Tf136ULQZRIGWkYOfOjp8PupaH9JDvdmTdxeUFykI=&originalReferer=&sessionRedirect=https%3A%2F%2Fwww.linkedin.com%2Fcompany%2Fregisters-of-scotland>

Please consider the environment – do you really need to print this email?

This e-mail (and any files or other attachments transmitted with it) is intended solely for the attention of the addressee(s). Unauthorised use, disclosure, storage, copying or distribution of any part of this e-mail is not permitted. If you are not the intended recipient please destroy the email, remove any copies from your system and inform the sender immediately by return. 

Registers of Scotland does not accept any liability or responsibility for any damage caused by any virus transmitted by this email or for changes made to this e-mail after it was sent. 
All communications to or from Registers of Scotland may be automatically logged, monitored and/or recorded in order to secure the effective operation of the system and for other lawful purposes. The views or opinions contained within this e-mail may not necessarily reflect those of the Keeper of the Registers of Scotland.

**Comment by Mukheem** [comment]
@r1chardj0n3s ,

I mean It is getting difficult to understand by audience how to set up provider states. Any how, I went thru your code and completed by task.

But I've a question though.

Say, Consumer is created with some dummy data. and now I am executing Provider side testing.
Here, I need to fetch data from database( something like `select empname from emp where id = 1` )
so my request would take `empname `from this output and hit the provider to get response.

How are we gonna do this? because PACT can be generated with any random data. Provider environment may or may not have that data to complete testing successfully. So, what we can do is before hitting the provider we can pull data from DB and hit the provider. How can I achieve this in pactman.


P.S.: If we do this in provider state and return `empname` as state's  response, I could be used no where. because return response from provider state is used no where.

**Comment by r1chardj0n3s** [comment]
Yep! Your consumer *must* make no assumptions about the provider's state *except that which may be controlled through an explicit pact provider state*. So, if you have a consumer pact whose response relies on a particular provider state, like an employee with a specific name matching a specific id, then you *must* have that pact use a provider state like `given an employee with id 1 is called 'Alex'`. Either the pact must be specified in such a way that variations in the provider response are allowed (i.e. match by type only, or match strings by regular expression) OR you must control the provider's state through pact provider states.

**Comment by Mukheem** [comment]
@r1chardj0n3s , Let me put it in another way.

For example, Provider needs a string as an Input to fetch the response and that input should exist in DB as well. But our pact is created with some dummy data say 'ABCD'. so I need to pass 'Alex' in my request to before i hit Provider URL. How shall I do that ?

Do i need to change data in PACT manually before executing Provider side testing ? Is this the only way ?

**Comment by ryallsa** [comment]
Thanks for contacting Registers of Scotland, your email has been delivered to your intended recipient(s), who will be in touch as soon as they can.

In order to focus on safeguarding the wellbeing of our staff, maintaining our essential business activity, and operating in accordance with government guidelines during this public health emergency, we ask that you direct your enquiries as follows:

A specific case or enquiry – please resend your email to our Customer Services<mailto:customer.services@ros.gov.uk> team who will be in touch.

Any other general enquiry – please resend your email to Covid19enquiries@ros.gov.uk so it can be directed to the correct person.

Thank You

- - - - - - - - - - - - - - - - - - -
Registers of Scotland
- - - - - - - - - - - - - - - - - - -

www.ros.gov.uk<https://www.ros.gov.uk>

[cid:image539684.PNG@576e9316.439e51dc]<https://www.ros.gov.uk/>    [cid:imagec9fac1.PNG@23b8e3d7.4596bb8f] <https://www.facebook.com/registersofscotland/>   [cid:image6ef57a.PNG@b4879b09.4981ea8f] <https://twitter.com/RegistersOfScot>   [cid:image27f818.PNG@d8128bbe.45903695] <https://www.youtube.com/channel/UCsvdb1Mw7n-shANwtFxrDMQ>   [cid:imagea2f5d9.PNG@d4334e24.498a1a27] <https://www.linkedin.com/authwall?trk=gf&trkInfo=AQEFPBtu7CCWwQAAAWNewfqoDlR1tdKRE7wGUu67suRzsyti8TMecqKnr1l97Cm06GPZkKXX2TXzf5g1bQO13VHKbYipr9Tf136ULQZRIGWkYOfOjp8PupaH9JDvdmTdxeUFykI=&originalReferer=&sessionRedirect=https%3A%2F%2Fwww.linkedin.com%2Fcompany%2Fregisters-of-scotland>

Please consider the environment – do you really need to print this email?

This e-mail (and any files or other attachments transmitted with it) is intended solely for the attention of the addressee(s). Unauthorised use, disclosure, storage, copying or distribution of any part of this e-mail is not permitted. If you are not the intended recipient please destroy the email, remove any copies from your system and inform the sender immediately by return. 

Registers of Scotland does not accept any liability or responsibility for any damage caused by any virus transmitted by this email or for changes made to this e-mail after it was sent. 
All communications to or from Registers of Scotland may be automatically logged, monitored and/or recorded in order to secure the effective operation of the system and for other lawful purposes. The views or opinions contained within this e-mail may not necessarily reflect those of the Keeper of the Registers of Scotland.

**Comment by r1chardj0n3s** [comment]
The consumer (you) and the provider (also you? in some cases this is someone else) must come to some agreement on what data the consumer can use and rely on being in the provider's state. That may involve the provider creating a pact provider state that you can specify in your pact so that the provider creates that agreed state (in their database, or however their state is persisted) before you exercise the pact. This is the whole purpose of provider states.

**Comment by Mukheem** [comment]
Thanks @r1chardj0n3s
