### ISSUE TITLE
Eachlike minimum=1 is not working 

### ISSUE THREAD

**Issue by jitindoriya07** [reecetech/pactman#93]
I have added expected result as 
```
expected = {
            "metaData": EachLike({

                "attributename": "visitquality",
                "dblabel": "visitquality",
                "uilabel": "Website Visit Quality",
                "datatype": "varchar(255)",

                "isprimarykey": Term(True | False, True),
                "ismandatory": Term(True | False, True),
                "isdomainvalue": Term(True | False, True),

                "ishidden": Term(True | False, True),
                "attributetype": Term("Peak Standard|Custom", "Peak Standard"),
                "attributeid": 19500,
                "audcreatedby": "Peak",
                "audcreatedat": Term("\d+-\d+-\d+T\d+:\d+:\d+.\d+Z", "2020-04-21T09:08:22.557Z"),

                "dblabeldescription": "Website Visit Quality"
            },minimum=1)}
```
Error from verification:
```
 Failed: body.metaData[9].dblabeldescription not correct type (null is not string) at body.metaData[9].dblabeldescription
```
But since I have mentioned minimum=1, still it failed

**Comment by r1chardj0n3s** [comment]
Without seeing the data that was rejected, I can only guess but it looks like the 10th element in the `metaData` array received has a null value for `dblabeldescription` rather than a string.

pactman has test cases for this feature so I'm reasonably sure it's working.

**Comment by jitindoriya07** [comment]
Yeah @r1chardj0n3s  you are correct about so , It should be not failing when only one array has a null value for `dblabeldescription` whereas atleast one of the element has string type

**Comment by r1chardj0n3s** [comment]
I think you are misunderstand what the minimum=1 is for. It's not to indicate "at least one entry in the array must satisfy these requirements, and other elements may break the rules specified", it's "this array's entries must satisfy these requirements, and there must be at least one entry".

If you do not wish to assert that `dblabeldescription` is always a string, then do not include it in your rule. It will then be ignored.

Also, `Term(True | False, True)` is not valid - I'm actually surprised you don't get an error. The `Term` matcher is to be used to match a regular expression. If you want to match a boolean then just supply a boolean value. Since you're specifying EachLike then any boolean type value will satisfy the rule.

**Comment by jitindoriya07** [comment]
Thanks @r1chardj0n3s for explanation
